services:
  - type: web
    name: flip-coin-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
